/**
 * This file is automatically created by Recurly's OpenAPI generation process
 * and thus any edits you make by hand will be lost. If you wish to make a
 * change to this file, please create a Github issue explaining the changes you
 * need and we will usher them to the appropriate places.
 */
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Newtonsoft.Json;

namespace Recurly.Resources
{
    [ExcludeFromCodeCoverage]
    public class GiftCard : Resource
    {

        /// <value>The remaining credit on the recipient account associated with this gift card. Only has a value once the gift card has been redeemed. Can be used to create gift card balance displays for your customers.</value>
        [JsonProperty("balance")]
        public decimal? Balance { get; set; }

        /// <value>When the gift card was canceled.</value>
        [JsonProperty("canceled_at")]
        public DateTime? CanceledAt { get; set; }

        /// <value>Created at</value>
        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <value>3-letter ISO 4217 currency code.</value>
        [JsonProperty("currency")]
        public string Currency { get; set; }

        /// <value>When the gift card was sent to the recipient by Recurly via email, if method was email and the "Gift Card Delivery" email template was enabled. This will be empty for post delivery or email delivery where the email template was disabled.</value>
        [JsonProperty("delivered_at")]
        public DateTime? DeliveredAt { get; set; }

        /// <value>The delivery details for the gift card.</value>
        [JsonProperty("delivery")]
        public GiftCardDelivery Delivery { get; set; }

        /// <value>The ID of the account that purchased the gift card.</value>
        [JsonProperty("gifter_account_id")]
        public string GifterAccountId { get; set; }

        /// <value>Gift card ID</value>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <value>Object type</value>
        [JsonProperty("object")]
        public string Object { get; set; }

        /// <value>The product code or SKU of the gift card product.</value>
        [JsonProperty("product_code")]
        public string ProductCode { get; set; }

        /// <value>The ID of the invoice for the gift card purchase made by the gifter.</value>
        [JsonProperty("purchase_invoice_id")]
        public string PurchaseInvoiceId { get; set; }

        /// <value>The ID of the account that redeemed the gift card redemption code.  Does not have a value until gift card is redeemed.</value>
        [JsonProperty("recipient_account_id")]
        public string RecipientAccountId { get; set; }

        /// <value>When the gift card was redeemed by the recipient.</value>
        [JsonProperty("redeemed_at")]
        public DateTime? RedeemedAt { get; set; }

        /// <value>The unique redemption code for the gift card, generated by Recurly. Will be 16 characters, alphanumeric, displayed uppercase, but accepted in any case at redemption. Used by the recipient account to create a credit in the amount of the `unit_amount` on their account.</value>
        [JsonProperty("redemption_code")]
        public string RedemptionCode { get; set; }

        /// <value>The ID of the invoice for the gift card redemption made by the recipient.  Does not have a value until gift card is redeemed.</value>
        [JsonProperty("redemption_invoice_id")]
        public string RedemptionInvoiceId { get; set; }

        /// <value>The amount of the gift card, which is the amount of the charge to the gifter account and the amount of credit that is applied to the recipient account upon successful redemption.</value>
        [JsonProperty("unit_amount")]
        public decimal? UnitAmount { get; set; }

        /// <value>Last updated at</value>
        [JsonProperty("updated_at")]
        public DateTime? UpdatedAt { get; set; }

    }
}
