#!/usr/bin/env bash
set -e

CONFIGURATION=${1:-Debug}

if [ ! -d "testrunner" ]; then
  nuget restore Recurly.sln
  nuget install xunit.runner.console -Version 2.4.0 -OutputDirectory testrunner
fi

msbuild /p:Configuration=$CONFIGURATION Recurly.sln
