#!/usr/bin/env bash

if test -f ./bin/dotnet-format; then
  if [ "$1" == "--check" ]; then
    ./bin/dotnet-format --check --dry-run
  else
    ./bin/dotnet-format
  fi
else
  echo "[WARNING] dotnet formatter not found"
fi
