#!/usr/bin/env bash
set -e

if ! hash brew 2>/dev/null; then
  echo "✖ Homebrew not found. Please install: https://brew.sh/"
  exit 1
else
  echo "✓ Found homebrew"
fi

if ! hash dotnet 2>/dev/null; then
  read -p "✖ 'dotnet' not found. Would you like to install it? [Y/n] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    curl -o /tmp/dotnet.pkg https://download.microsoft.com/download/E/8/A/E8AF2EE0-5DDA-4420-A395-D1A50EEFD83E/dotnet-sdk-2.1.401-osx-gs-x64.pkg
    echo "Installing dotnet requires sudo..."
    sudo installer -pkg /tmp/dotnet.pkg -target /
    echo "✓ Installed dotnet"
  else
    exit 1
  fi
else
  echo "✓ Found dotnet"
fi
