#!/usr/bin/env bash
set -e

if ! hash brew 2>/dev/null; then
  echo "✖ Homebrew not found. Please install: https://brew.sh/"
  exit 1
else
  echo "✓ Found homebrew"
fi

if ! hash dotnet 2>/dev/null; then
  read -p "✖ 'dotnet' not found. Would you like to install it? [Y/n] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    curl -o /tmp/dotnet.pkg https://download.visualstudio.microsoft.com/download/pr/4850aa8f-44a9-4c4a-9961-f18aa4d90ceb/07d790444f3ba6b412a76d6f1aced338/dotnet-sdk-2.2.105-osx-x64.pkg
    echo "Installing dotnet requires sudo..."
    sudo installer -pkg /tmp/dotnet.pkg -target /
    echo "✓ Installed dotnet"
  else
    exit 1
  fi
else
  echo "✓ Found dotnet"
fi
