#!/usr/bin/env bash

set -e

# Usage
#
# ./release
#

cat ~/.nuget-token

if [ -f ~/.nuget-token ]; then
  api_token=$(cat ~/.nuget-token)
fi
# NUGET_TOKEN env var has precedence over ~/.nuget-token
api_token=${NUGET_TOKEN:-$api_token}

# Environment verification
if [ -z "$api_token" ]; then
  echo "API token must be set in ~/.nuget-token or NUGET_TOKEN environment variable. Aborting."
  exit 1
fi


#clean
rm -rf "$(pwd)"/Recurly/bin/

#publish
dotnet pack -c Release
dotnet build -c Release
dotnet nuget push "$(pwd)"/Recurly/bin/Release/Recurly.*.nupkg -s https://api.nuget.org/v3/index.json -k "$api_token"

