#!/usr/bin/env bash

# First check formatting
echo "Checking style..."
if ./scripts/format --check; then
  echo "Style check passed"
else
  echo "Code does not conform to style guide. To autoformat, run './scripts/format'."
  exit 1
fi

set -e

# all options just a passthrough for `dotnet test` options
# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test

# e.g. to output test run to html:
# ./scripts/test --logger html

dotnet test Test/Recurly.Test.csproj "$@"

